### ISSUE TITLE
Add more detail around contrib scenarios

### ISSUE THREAD

**Issue by phenixblue** [tmobile/magtape#54]
**What would you like to be added**:

Need to add additional documentation around different contributor scenarios.

Examples:
- [X] Run linting/formatting if you edit Python files (#80)
- [X] Run linting/formatting if you edit Rego files (#60/#80)
- [X] Rebuild install manifest if you edit YAML manifests (#80)

**Why is this needed**:

Lower barrier to entry for new contributors and to help me not have to remember!
